name: CI

on:
  push:
    runs-on: ubuntu-latest


    steps:
    #Checks-out your repo under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    #Setup Python 3.6 environment
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"

    #Install dependencies
    - name: Install dependencies
      run: |
        python test_app.py

    - name: Build Docker Image and Push to Dockerhub
      uses: mr-smithers-execellent/docker-build-push@v5
      with:
        image: chash07/demo-app
        tags: latest
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
